### PR TITLE
ENTESB-4023 - Fix creation of .zip distro

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by sjavurek** [comment]
ok to test

**Comment by sjavurek** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Pull request merged**
