### PR TITLE
PATCH-1025

### PR DESCRIPTION
**Pull request by chirino**
Fix attempt fro ENTESB-4610: Fabric gateway fails because of incorrect use of ShutdownTracker.
- Tightens up synchronization of the socket tracking.

### CODE REVIEW

**Comment by janstey** [comment]
retest this please

**Comment by sjavurek** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by grgrzybek** [comment]
Closed - PR included in https://github.com/jboss-fuse/fabric8/pull/494

**Comment by chirino** [comment]
#494 was merged into 6.3, but this one was targeted at 6.2.x

**Comment by chirino** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Pull request closed without merging**
