### PR TITLE
Entesb 1709 process manager

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Pull request merged**
