### PR TITLE
ENTESB-4159 - Fix fabric-camel behavior

### PR DESCRIPTION
**Pull request by paoloantinori**
Fabric-Camel endpoint were not re-published in case of lost connection with ZK.

### CODE REVIEW

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Pull request merged**
