### PR TITLE
[ENTESB-2754] Avoid going to remote repositories if the non-snapshot art...

### PR DESCRIPTION
**Pull request by gnodet**
...ifact is present in the system repository

### CODE REVIEW

**Comment by grgrzybek** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by gnodet** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Pull request closed without merging**
