### PR TITLE
ENTESB-7259 - fix for duplicated broker

### PR DESCRIPTION
**Pull request by paoloantinori**
This has a corresponding commit in `fuse` project, to alter the `etc/io.fabric8.mq.fabric.server-broker.cfg` file.

### CODE REVIEW

**Review by grgrzybek — APPROVED** [review]
wow - that's great oneliner!

**Comment by paoloantinori** [comment]
Fabric Managed broker does strange things...

**Comment by paoloantinori** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Review by johnpoth — APPROVED** [review]

**Pull request merged**
