### PR TITLE
ENTESB-3949 - fabric-agent - force re-reading of internal maven repos

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by kevinearls** [comment]
test this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by janstey** [comment]
ok to test

**Comment by grgrzybek** [comment]
Merged with another PR:
- https://github.com/jboss-fuse/fabric8/commit/c065ff94164b5e2849eeb2da4503958070a07067

**Pull request closed without merging**
