### PR TITLE
[PATCH-1970][ENTESB-6764] Swagger Feature throws NullPointerException if using absolute path in server address

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.jboss.org/browse/ENTESB-6764
https://issues.jboss.org/browse/PATCH-1970

Upgrade to swagger-jaxrs 1.3.12_3

(cherry picked from commit 8512c166dc02de271430aaa365c652d9a7606d7f)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by tadayosi** [comment]
retest this please

**Comment by tadayosi** [comment]
retest this please

**Comment by tadayosi** [comment]
retest this please

**Comment by tadayosi** [comment]
https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-6.2.x.redhat-patch-pullreq/1668/console
01:30:55 [INFO] ------------------------------------------------------------------------
01:30:55 [INFO] BUILD SUCCESS
01:30:55 [INFO] ------------------------------------------------------------------------
01:30:55 [INFO] Total time: 28:47 min
01:30:55 [INFO] Finished at: 2017-06-07T21:33:08-04:00
01:30:56 [INFO] Final Memory: 524M/895M
01:30:56 [INFO] ------------------------------------------------------------------------

**Pull request merged**
