### PR TITLE
[ENTESB-2391] Remove duplicate default tags from profile names (like cxf...

### PR DESCRIPTION
**Pull request by grgrzybek**
...-camel-cxf-xxx)

### CODE REVIEW

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Pull request closed without merging**
