### PR TITLE
ENTESB-6666 -[6.3]  Fix issue with SCR, ConfigAdmin and factoryPids.

### PR DESCRIPTION
**Pull request by paoloantinori**
Upgrade Felix SCR

### CODE REVIEW

**Comment by paoloantinori** [comment]
linked to PR on karaf: https://github.com/jboss-fuse/karaf/pull/175

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Retest this please

**Comment by paoloantinori** [comment]
This will fail until a new Perfectus build so that it will start using a new Karaf tag (`v > 630247`).

Currently waiting for other fixes before running a new Perfectus

**Comment by paoloantinori** [comment]
retest this please

**Pull request merged**
