### PR TITLE
Patch 1847

### PR DESCRIPTION
**Pull request by paoloantinori**
@grgrzybek this has already been merged on 6.3. Could you approve this please?

### CODE REVIEW

**Review by grgrzybek — APPROVED** [review]

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
this is an odd failure

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Pull request closed without merging**
