### PR TITLE
Ggrzybek fixes

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by janstey** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
It is merged.

**Comment by grgrzybek** [comment]
Thanks very much @janstey for retesting this!
I hope everything in perfectus built fine.

**Pull request closed without merging**
