### PR TITLE
ENTESB-9990 Remove the narayana artifacts from the spring-boot-depend…

### PR DESCRIPTION
**Pull request by zhfeng**
…encies and they should depend on the narayana-spring-boot

### CODE REVIEW

**Comment by ffang** [comment]
Hi @zhfeng ,

A quick question, with this change, I think the result is that the narayan dependencies will be completely removed from fabric8-project-bom-camel-spring-boot, but we still need those(with aligned version), right?

Freeman

**Comment by zhfeng** [comment]
@ffang I'm not very sure that why we need the narayana dependencies here, IMO it is only needed if using the transaction manager in the camel and this should depends on the me.snowdrop.narayana-spring-boot starter.

**Comment by ffang** [comment]
@zhfeng the problem is that with your change, there's no org.jboss.narayana.jta:* and org.jboss.narayana.jts:* in fabric8-project-bom-camel-spring-boot at all, so if downstream projects/users which/who previously import this bom and use org.jboss.narayana.jta/org.jboss.narayana.jts they will run into problem.

If you believe the correct narayana version should be from me.snowdrop.narayana-spring-boot starter, I think you also should add that in the bom generation part of fabric8/pom.xml(sundr-maven-plugin:generate-bom) to ensure the generated fabric8-project-bom-camel-spring-boot also contains org.jboss.narayana.jta/org.jboss.narayana.jts, which will keep backwards compatibility.

My 2 cents

Freeman

**Comment by ffang** [comment]
@zhfeng , I figured out that the "override" configuration for sundr-maven-plugin:generate-bom can do the trick. The change should be like
```
diff --git a/pom.xml b/pom.xml
index 9d9c89c..cf7b1bb 100644
--- a/pom.xml
+++ b/pom.xml
@@ -146,6 +146,7 @@
         <jetty.version>8.1.17.v20150415</jetty.version>
 
         <narayana-spring-boot.version>1.0.3.fuse-730033</narayana-spring-boot.version>
+        <narayana.version>5.9.0.Final-redhat-00001</narayana.version> 
 
 <!--
         We've released a new version of gitective (0.9.50) with the latest jgit support (4.10.0.201712302008-r)
@@ -1489,6 +1490,17 @@
                               <override>
                                   <dependencies>
                                       <includes>
+                                          <include>org.jboss.narayana.jta:jdbc</include>
+                                          <include>org.jboss.narayana.jta:jms</include>
+                                          <include>org.jboss.narayana.jta:jta</include>
+                                          <include>org.jboss.narayana.jts:narayana-jts-integration</include>
+                                      </includes>
+                                  </dependencies>
+                                  <version>${narayana.version}</version>
+                              </override>
+                              <override>
+                                  <dependencies>
+                                      <includes>
                                           <include>org.springframework.cloud:spring-cloud-stream-binder-kafka-test-support</include>
                                       </includes>
                                   </dependencies>
```

Cheers
Freeman

**Comment by zhfeng** [comment]
Thanks @ffang I just apply your changes and it looks good to me !

**Comment by zhfeng** [comment]
@ffang I change to import the narayana artifacts from the me.snowdrop.narayana-spring-boot-core as these artifacts have been removed from the spring-boot-dependencies 2.x

**Comment by ffang** [comment]
Thanks @zhfeng!  merged!

**Pull request merged**
