### PR TITLE
Revert "Revert "track down intermittent failure of ServiceFactoryTest…

### PR DESCRIPTION
**Pull request by gtully**
…. Root cause was partial sequential ephemeral node creation leading to duplicate state and conditional guarantee delete rather than letting curator take care of reconnect. Fix is to use hidden uuid nodestate field on znode creation such that duplicates can be suppressed""

This reverts commit be5e23cfacc011db55f858ccf989e817728c015e.

https://issues.jboss.org/browse/ENTESB-4437 - good for 6.3 - 6.2.1 will ignore missing json fields

### CODE REVIEW

**Comment by gtully** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by chirino** [comment]
ok to test

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
Closed - PR included in https://github.com/jboss-fuse/fabric8/pull/494

**Pull request closed without merging**
