### PR TITLE
ENTESB-4012 - Maven Proxy Servlet - remove accidental caching behavior

### PR DESCRIPTION
**Pull request by paoloantinori**
(cherry picked from commit 6de6d26908b4991f1247feae40ca36c301a34e41)

### CODE REVIEW

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by paoloantinori** [comment]
retest this please

**Comment by jsherman1** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Pull request merged**
