### PR TITLE
ENTESB-6653:profile-edit input valiation

### PR DESCRIPTION
**Pull request by RaiSaurabh**
Updated the property value from null to empty so that property value could be set.

### CODE REVIEW

**Review by paoloantinori — CHANGES_REQUESTED** [review]
This is not correct. The sample invocation you have in the JIRA case is invalid. You are not assigning a value and not even putting a `=` single in the expression.

This is an input validation issue. You should report an error for invalid invocations like the one in your example.

**Review by RaiSaurabh — COMMENTED** [review]
Updated the code as commented.

**Comment by vrlgohel** [comment]
@RaiSaurabh , can you 'fixup' or 'squash'  commits ? That way it would be more easier to review. All the iTests should probably be running fine without any issues. Did you check ? 

@paoloantinori, please correct me on this as i believe it helps us to review & merge better.

**Comment by RaiSaurabh** [comment]
Will create a new PR as as this is messed up due to multiple commits.

**Pull request closed without merging**
