### PR TITLE
ENTESB-3913 - getVersion - relaxed concurrency for performance

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by sjavurek** [comment]
retest this please

**Comment by janstey** [comment]
Merged https://github.com/jboss-fuse/fabric8/commit/27a949de6bbe6d8940d68f3adfd00dccbd8b074d

**Pull request closed without merging**
