### PR TITLE
https://issues.jboss.org/browse/FABRIC-1238 - handle zk outage for mq services

### PR DESCRIPTION
**Pull request by dejanb**

### CODE REVIEW

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by dejanb** [comment]
retest this please

**Comment by dejanb** [comment]
retest this please

**Comment by dejanb** [comment]
retest this please

**Comment by dejanb** [comment]
retest this please

**Comment by janstey** [comment]
BTW if this one if for a 6.2.0 patch, it should be merged to 1.2.0.redhat-6-2-0-patch branch. 1.2.0.redhat-6-2-x-patch is needed as well, but this one is for 6.2.1 release in fall.

**Comment by dejanb** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by dejanb** [comment]
retest this please

**Comment by grgrzybek** [comment]
continued here: https://github.com/jboss-fuse/fabric8/pull/415

**Pull request closed without merging**
