### PR TITLE
ENTESB-4012 - Maven Proxy Servlet - remove accidental caching behavior

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by janstey** [comment]
ok to test

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by sjavurek** [comment]
retest this please

**Comment by grgrzybek** [comment]
Closed - PR included in https://github.com/jboss-fuse/fabric8/pull/494

**Pull request closed without merging**
