### PR TITLE
[ENTESB-3534]Profile-edit -c prints null version in the output

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by jimmidyson** [comment]
Merged.

**Pull request closed without merging**
