### PR TITLE
ENTESB-6152 - fix for previous commit. Now using a mutable list and r…

### PR DESCRIPTION
**Pull request by johnpoth**
…enamed ProjectDeployerMXBean method as to not break backward compatibility

https://issues.jboss.org/browse/ENTESB-5095?focusedCommentId=13319004&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13319004

### CODE REVIEW

**Comment by johnpoth** [comment]
PATCH ticket: https://issues.jboss.org/browse/PATCH-1466

**Review by janstey — APPROVED** [review]
Tried deploying camel-log-wiki after this change and it worked fine.

**Comment by janstey** [comment]
@jpoth could you also cherry-pick to 1.2.0.redhat-6-3-x-R1 once this is in? We'll need to rebuild the R1 patch.

**Comment by janstey** [comment]
retest this please

**Pull request merged**
