### PR TITLE
[ENTESB-4288]fabric8 maven proxy should honor multiple roles and it s…

### PR DESCRIPTION
**Pull request by ffang**
…hould be configurable

### CODE REVIEW

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by grgrzybek** [comment]
Merged with another PR:
- https://github.com/jboss-fuse/fabric8/commit/789992218e8c7148bbe1c84e3aa0370817275257

**Pull request closed without merging**
