### PR TITLE
[ENTESB-7192] Override client destination address before going throug…

### PR DESCRIPTION
**Pull request by johnpoth**
…h the interceptor chain when using FabricFailOverFeature

(cherry picked from commit e6b7bb12c56e5d7fc4ad8e973415967bd61ecf39)

https://issues.jboss.org/browse/ENTESB-7192
https://issues.jboss.org/browse/PATCH-2256

Thanks!

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by johnpoth** [comment]
retest this please

**Comment by johnpoth** [comment]
retest this please

**Comment by johnpoth** [comment]
retest this please

**Comment by johnpoth** [comment]
Full build with tests passing locally

**Pull request merged**
