### PR TITLE
ENTESB-3682 - respect minPort in case of joined nodes

### PR DESCRIPTION
**Pull request by paoloantinori**
This is open on 6.2.x but, when validated, it's been already requested on the PATCH branch for 6.2.0

### CODE REVIEW

**Comment by sjavurek** [comment]
retest this please

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
retest this please

**Comment by grgrzybek** [comment]
Merged with another PR
- https://github.com/jboss-fuse/fabric8/commit/14844eac3237aa421c604225f1467091b78a94c9
- https://github.com/jboss-fuse/fabric8/commit/b07b065f043d3c1e40b4964775b50cadd6bdf351

**Pull request closed without merging**
