### PR TITLE
[ENTESB-2772]consider the case that list of new parents containing one o...

### PR DESCRIPTION
**Pull request by ffang**
...f the older ones

### CODE REVIEW

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Pull request merged**
