### PR TITLE
PATCH-1568 - ENTESB-6183 - Fix for SecurityManager

### PR DESCRIPTION
**Pull request by paoloantinori**
This has a corresponding PR on Karaf:

https://github.com/jboss-fuse/karaf/pull/135

### CODE REVIEW

**Review by janstey — APPROVED** [review]
:+1:

**Comment by tadayosi** [comment]
retest this please

**Comment by tadayosi** [comment]
Looks like the same tests keep failing. We need to fix them before merging it.
- io.fabric8.patch.itests.PatchBundlesCommandIntegrationTest(karaf).io.fabric8.patch.itests.PatchBundlesCommandIntegrationTest
- io.fabric8.patch.itests.PatchBundlesIntegrationTest(karaf).io.fabric8.patch.itests.PatchBundlesIntegrationTest
- io.fabric8.patch.itests.PatchFilesIntegrationTest(karaf).io.fabric8.patch.itests.PatchFilesIntegrationTest

**Comment by paoloantinori** [comment]
This probably requires a perfectus release so that Fabric8 will start using a tag containing the corresponding code merged in Karaf.

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
```
 Could not find artifact org.apache.karaf.jaas:org.apache.karaf.jaas.command:jar:2.4.0.redhat-630195 in jboss.ea.repo (https://repository.jboss.org/nexus/content/groups/ea/), Could not find artifact org.apache.karaf.jaas:org.apache.karaf.jaas.command:jar:2.4.0.redhat-630195 in maven.central.repo (http://repo1.maven.org/maven2/)]
```

**Comment by paoloantinori** [comment]
bumped karaf tag, it should find it now

**Comment by paoloantinori** [comment]
this never built successfully. it shouldn't have been merged

**Comment by tadayosi** [comment]
@paoloantinori Yes, it built successfully at least once 😄  https://10.8.63.16/job/fabric8-6.3.x.redhat-pullrequest/852/

**Comment by paoloantinori** [comment]
mmmm looking at the link you posted it wasn't successful. is that the correct link?

**Comment by tadayosi** [comment]
Ahhh, you are right... I was mixed up. I should have checked the console log. I'll revert it.

**Comment by paoloantinori** [comment]
Ok, np. I'm planning  to fix this properly this morning. Thanks for verifying this.

**Pull request merged**
