### PR TITLE
ENTESB-1709 removing unsupported fabric bits

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
ok to test

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by chirino** [comment]
I'm going to break this PR up into multiple parts to see if we can narrow down which part is causing it to fail.

**Pull request closed without merging**
