### PR TITLE
ENTMQ-1107 - ensure broker blocked in start on store lock acquire can…

### PR DESCRIPTION
**Pull request by gtully**
… be gracefully stopped on shutdown - slave mode broker

### CODE REVIEW

**Comment by gtully** [comment]
ready to test. try again

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by gtully** [comment]
https://github.com/jboss-fuse/fabric8/commit/35366182350ed83392cf4b0d0c6e027841702688

**Pull request closed without merging**
