### PR TITLE
[ENTESB-3361] Update agent status not faster than every 2 seconds

### PR DESCRIPTION
**Pull request by grgrzybek**
(cherry picked from commit 461bd6b6878d42c46e396319bf30d8ced7b07224)

### CODE REVIEW

**Comment by aileenc** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to testok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by grgrzybek** [comment]
ok to test

**Comment by janstey** [comment]
Having issues with jenkins slaves... will test manually.

**Comment by janstey** [comment]
Manual test was a success:
(05:12:01 PM) ggrzybek: janstey, one more thing
(05:12:03 PM) ggrzybek: [INFO] BUILD SUCCESS
(05:12:05 PM) ggrzybek: [INFO] ------------------------------------------------------------------------
(05:12:07 PM) ggrzybek: [INFO] Total time: 01:54 h

**Pull request merged**
