### PR TITLE
Patch 1847

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Review by janstey — APPROVED** [review]
:+1:

**Comment by janstey** [comment]
retest this please

**Review by janstey — APPROVED** [review]
Let's try again...

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
NO idea why we were getting this:

17:09:05 remote: error: GH006: Protected branch update failed for refs/heads/1.2.0.redhat-6-2-x-patch.        
17:09:05 remote: error: At least one approved review is required by reviewers with write access.

So merged manually.

**Comment by paoloantinori** [comment]
Yay!

**Pull request merged**
