### PR TITLE
ZKComponentSupport now also looks at env vars to set zookeeper url

### PR DESCRIPTION
**Pull request by luksa**
This makes it possible to use the Master&Fabric components when Fuse is running inside OpenShift/Kubernetes

### CODE REVIEW

**Comment by jimmidyson** [comment]
@luksa - LGTM thanks!

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by gnodet** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
Merged

**Pull request closed without merging**
