### PR TITLE
[ENTESB-3302][ENTESB-2636] Trying to fix swagger in Fuse - 1st attemp…

### PR DESCRIPTION
**Pull request by grgrzybek**
…t to integrate with swagger-ui

### CODE REVIEW

**Comment by chirino** [comment]
ok to test

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Pull request merged**
