### PR TITLE
ENTESB-1758 - Prevent risk of NPE

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by grgrzybek** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Pull request merged**
