### PR TITLE
Fixes ENTESB-2954: with this change the InstanceAlreadyExistsException e...

### PR DESCRIPTION
**Pull request by chirino**
...rrors don't start as soon as the fabric is created.

### CODE REVIEW

**Comment by chirino** [comment]
retest this please

**Comment by aileenc** [comment]
ok to test

**Comment by chirino** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Pull request closed without merging**
