### PR TITLE
ENTESB-4712 - Remove references to RHAccess

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
Merged [here](https://github.com/jboss-fuse/fabric8/commit/fd48b959c27430a4fdd2ec8c78c7ee03b2253baf)

**Pull request closed without merging**
