### PR TITLE
Use version 1.2.0.redhat-SNAPSHOT

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by kevinearls** [comment]
test this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by kevinearls** [comment]
test this please

**Comment by janstey** [comment]
ok to test

**Comment by grgrzybek** [comment]
please don't merge this one yet

**Comment by grgrzybek** [comment]
It's not actually needed ;)

**Pull request closed without merging**
