### PR TITLE
PATCH-1849 - ENTESB-6510 - swagger-cxf fix for basePath

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by paoloantinori** [comment]
this is also failing until a new perfectus build that bumps Karaf to a tag `> 630247`

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by tadayosi** [comment]
retest this please

**Pull request merged**
