### PR TITLE
[ENTESB-5395]upgrade to use blueprint.core 1.4.5 to pick up the fix f…

### PR DESCRIPTION
**Pull request by ffang**
…or ARIES-1395

### CODE REVIEW

**Comment by ffang** [comment]
retest this please

**Comment by grgrzybek** [comment]
@ffang fyi, because ARIES-1503 wasn't fixed with 1.5.0, if doing further upgrades of bp.core, we'll have to upgrade to at least 1.6.2. But it's not necessary now.

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
@grgrzybek I just checked the code in org.apache.aries.blueprint.core-1.5.0-sources.jar, the required fix is already there. So it just the jira ticket ARIES-1503 not mark resolved with proper version.
Thanks for the reminder BTW.

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Pull request merged**
