### PR TITLE
Entesb 2932

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
Hey @chirino  there's a compilation time failure, due to checked exceptions declared in `throws` that are not taken care of in the invoker methods. Can you have a look?

**Comment by chirino** [comment]
fixed that build issue.  lets hope it passes the CI build.

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Pull request merged**
