### PR TITLE
ENTESB-4369 - Set explicit  startup level for karaf feature.

### PR DESCRIPTION
**Pull request by paoloantinori**
(cherry picked from commit c9df2ef527cbc34c05e384d376421076c2e2b930)

### CODE REVIEW

**Comment by paoloantinori** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by kevinearls** [comment]
ok to test

**Comment by paoloantinori** [comment]
retest this please

**Comment by jsherman1** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Pull request merged**
