### PR TITLE
ENTESB-4073 - fabric removed assertion related to duplicated assigned…

### PR DESCRIPTION
**Pull request by paoloantinori**
… profiles

### CODE REVIEW

**Comment by chirino** [comment]
ok to test

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
Closed - PR included in https://github.com/jboss-fuse/fabric8/pull/494

**Pull request closed without merging**
