### PR TITLE
[ENTESB-2949] Sometimes (rare) NullPointerException on broker startup an...

### PR DESCRIPTION
**Pull request by gnodet**
...d mq replicated container hangs on finalizing (stopping bundles)

### CODE REVIEW

**Comment by gnodet** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by gnodet** [comment]
The problem is actually a bit more complicated than I thought, this kind of commit will not be sufficient, I'll rework it.

**Comment by gnodet** [comment]
retest this please

**Pull request closed without merging**
