### PR TITLE
Configure the surefire plugin with rerunFailingTestsCount=2 to avoid …

### PR DESCRIPTION
**Pull request by chirino**
…failing on flaky tests.

### CODE REVIEW

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
Merged with another PR:
- https://github.com/jboss-fuse/fabric8/commit/1ccd3901ccb536b8e947b355f810a9d36f39e8c7
- https://github.com/jboss-fuse/fabric8/commit/1043e959877219a063f1b60232cba5eb56d039cf

**Pull request closed without merging**
