### PR TITLE
1.2.0.redhat 6 2 0 patch

### PR DESCRIPTION
**Pull request by dejanb**

### CODE REVIEW

**Comment by dejanb** [comment]
ok to test

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Pull request merged**
