### PR TITLE
ENTESB-4485 - getMavenRepoURIs() : Protecting from NPE

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by paoloantinori** [comment]
retest this please

**Comment by grgrzybek** [comment]
Closed - PR included in https://github.com/jboss-fuse/fabric8/pull/494

**Pull request closed without merging**
