### PR TITLE
[ENTESB-3342]Command fabric:join ignores option --non-managed

### PR DESCRIPTION
**Pull request by ffang**
(cherry picked from commit 734e89492b3edaa535c69bb9a295286716a56e5c)

### CODE REVIEW

**Comment by janstey** [comment]
ok to test

**Comment by janstey** [comment]
hmm should unlock this PR process since this branch is for 6.2.1 :-)

**Comment by janstey** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Pull request closed without merging**
