### PR TITLE
ENTESB-2242: Insight cleanup

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by grgrzybek** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Pull request merged**
