### PR TITLE
ENTESB-5381 - update to spring 3.2.16.RELEASE

### PR DESCRIPTION
**Pull request by janstey**

### CODE REVIEW

**Review by tadayosi — CHANGES_REQUESTED** [review]
https://issues.jboss.org/browse/PATCH-1430

Looks like some tests keep failing.

**Comment by tadayosi** [comment]
retest this please

**Comment by tadayosi** [comment]
retest this please

**Comment by janstey** [comment]
Works locally:

[INFO] Fabric8 :: Tooling :: JClouds All .................. SUCCESS [01:10 min]
[INFO] Fabric8 :: Tooling :: Fabric All ................... SUCCESS [  7.323 s]
[INFO] Fabric8 :: Tooling :: ServiceMix Facade (deprecated) SUCCESS [  2.111 s]
[INFO] Fabric8 :: Integration Tests :: TestKit ............ SUCCESS [  0.135 s]
[INFO] Fabric8 :: Integration Tests :: Arquillian ......... SUCCESS [  0.005 s]
[INFO] Fabric8 :: Integration Tests :: Arquillian :: Fabric8 Common SUCCESS [  0.077 s]
[INFO] Fabric8 :: Integration Tests :: Arquillian :: Remote Fabric8 Container SUCCESS [  0.063 s]
[INFO] Fabric8 :: Integration Tests :: AutoScale .......... SUCCESS [  0.004 s]
[INFO] Fabric8 :: Integration Tests :: AutoScale :: Common  SUCCESS [  0.121 s]
[INFO] Fabric8 :: Integration Tests :: Smoke .............. SUCCESS [  0.004 s]
[INFO] Fabric8 :: Integration Tests :: Smoke :: Karaf ..... SUCCESS [04:31 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:36 min
[INFO] Finished at: 2016-11-30T09:52:02-03:30
[INFO] Final Memory: 614M/1824M
[INFO] ------------------------------------------------------------------------

6.2.x jenkins jobs looks pretty flaky to me... its been failing for a while...

**Comment by janstey** [comment]
5 runs locally and they all worked fine :-)

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Review by tadayosi — APPROVED** [review]

**Comment by tadayosi** [comment]
Confirmed all the tests passed at least once :-)
https://10.8.63.16/job/fabric8-6.2.x.redhat-patch-pullreq/1557/

**Pull request merged**
