### PR TITLE
[ENTESB-1556] Aligning versions to pax-web 3.2.0. Only scala has duplicate bundles!

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by grgrzybek** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by ffang** [comment]
retest this please

**Pull request closed without merging**
