### PR TITLE
[ENTESB-2380] Previous commit always read from the beginning of the file

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gnodet** [comment]
please retest this

**Comment by gnodet** [comment]
retest this please

**Comment by gnodet** [comment]
retest this please

**Comment by janstey** [comment]
retest this please

**Comment by janstey** [comment]
Manually merged this one to get around sporadic issues so we can fix failing tests that happen every time:
io.fabric8.itests.smoke.karaf.ContainerUpgradeAndRollbackTest(karaf).testContainerUpgradeAndRollback
io.fabric8.itests.smoke.karaf.CreateChildContainerTest(karaf).testCreateChildWithMergedConfiguration
io.fabric8.itests.smoke.karaf.CreateChildContainerTest(karaf).testCreateChildContainerWithCustomZKServerPort
io.fabric8.itests.smoke.karaf.DeploymentAgentTest(karaf).testFeatureRepoResolution
io.fabric8.itests.smoke.karaf.DeploymentAgentTest(karaf).testResolveOptionalImports
io.fabric8.itests.smoke.karaf.EnsembleTest(karaf).testAddAndRemove

**Pull request merged**
