### PR TITLE
ENTESB-5191 - Apparent mismatch between command count with tab completion

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.jboss.org/browse/ENTESB-5191

### CODE REVIEW

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by tadayosi** [comment]
Close it as it's somehow stuck in CI build.

**Pull request closed without merging**
