### PR TITLE
Fix missing artifact pax-logging

### PR DESCRIPTION
**Pull request by ecervena**
Fix for fabric:create missing pax-logging artifact in build 091. https://issues.jboss.org/browse/ENTESB-2848

### CODE REVIEW

**Comment by janstey** [comment]
retest this please

**Comment by ecervena** [comment]
Would it be better to use ${pax.logging.version} instead of specific version?

**Comment by gnodet** [comment]
retest this please

**Comment by gnodet** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by gnodet** [comment]
retest this please

**Pull request closed without merging**
